import { extname } from "node:path";
import type {
  FileSummary,
  ProjectIndexEntry,
  ProjectRefreshInput,
  ProjectRefreshResult,
  ProjectScanInputFile,
  ProjectScanResult
} from "./types.js";

export function buildProjectScan(files: ProjectScanInputFile[]): ProjectScanResult {
  const index = files.map(buildProjectIndexEntry).sort((a, b) => a.path.localeCompare(b.path));
  const summaries = buildFileSummaries(index);

  return {
    index,
    summaries,
    projectMapMarkdown: buildProjectMapMarkdown(index, summaries)
  };
}

export function refreshProjectScan(input: ProjectRefreshInput): ProjectRefreshResult {
  const removed = new Set(input.removedPaths);
  const updatedEntries = input.updatedFiles.map(buildProjectIndexEntry);
  const updatedPaths = new Set(updatedEntries.map((entry) => entry.path));
  const index = [
    ...input.existingIndex.filter((entry) => !removed.has(entry.path) && !updatedPaths.has(entry.path)),
    ...updatedEntries
  ].sort((a, b) => a.path.localeCompare(b.path));
  const summaries = buildFileSummaries(index);

  return {
    index,
    summaries,
    projectMapMarkdown: buildProjectMapMarkdown(index, summaries),
    updatedPaths: [...updatedPaths].sort(),
    removedPaths: [...removed].sort(),
    unchangedCount: input.existingIndex.filter((entry) => !removed.has(entry.path) && !updatedPaths.has(entry.path)).length
  };
}

export function selectRelatedFilesFromScan(requirement: string, index: ProjectIndexEntry[], summaries: FileSummary[]): string[] {
  const tokens = extractScanTokens(requirement);
  const scores = new Map<string, number>();

  for (const entry of index) {
    const haystack = [entry.path, entry.category, ...entry.keywords].join(" ").toLowerCase();
    for (const token of tokens) {
      if (haystack.includes(token)) {
        scores.set(entry.path, (scores.get(entry.path) ?? 0) + 2 + priorityBonus(entry.path, token));
      }
    }
  }

  for (const summary of summaries) {
    const haystack = [summary.path, summary.role, ...summary.keywords, ...summary.features].join(" ").toLowerCase();
    for (const token of tokens) {
      if (haystack.includes(token)) {
        scores.set(summary.path, (scores.get(summary.path) ?? 0) + 3 + priorityBonus(summary.path, token));
      }
    }
  }

  return [...scores.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([path]) => path)
    .slice(0, 8);
}

export function buildProjectIndexEntry(file: ProjectScanInputFile): ProjectIndexEntry {
  const keywords = extractKeywords(file.path, file.content);

  return {
    path: file.path,
    extension: extname(file.path).replace(".", ""),
    category: categorize(file.path, keywords),
    keywords,
    size: file.size,
    lastModified: file.lastModified,
    hash: file.hash
  };
}

export function buildFileSummaries(index: ProjectIndexEntry[]): FileSummary[] {
  return index.map((entry) => buildFileSummary(entry, index));
}

function buildFileSummary(entry: ProjectIndexEntry, index: ProjectIndexEntry[]): FileSummary {
  const relatedFiles = index
    .filter((candidate) => candidate.path !== entry.path && candidate.category === entry.category)
    .map((candidate) => candidate.path)
    .slice(0, 8);

  return {
    path: entry.path,
    role: describeRole(entry),
    keywords: entry.keywords.slice(0, 20),
    features: inferFeatures(entry),
    relatedFiles
  };
}

export function buildProjectMapMarkdown(index: ProjectIndexEntry[], summaries: FileSummary[]): string {
  const categories = [...new Set(index.map((entry) => entry.category))].sort();
  const sections = categories.map((category) => {
    const entries = index.filter((entry) => entry.category === category).slice(0, 20);
    const files = entries
      .map((entry) => {
        const summary = summaries.find((item) => item.path === entry.path);
        return `- ${entry.path}: ${summary?.role ?? describeRole(entry)}`;
      })
      .join("\n");
    return `## ${category}\n${files}`;
  });

  return `# Dev Guard Project Map\n\nGenerated by \`dev-guard scan\`.\n\n${sections.join("\n\n")}\n`;
}

function categorize(path: string, keywords: string[]): string {
  const haystack = `${path} ${keywords.join(" ")}`.toLowerCase();
  const rules: Array<[string, RegExp]> = [
    ["auth", /auth|login|kakao|oauth|sign/],
    ["settings", /settings|setting|설정/],
    ["admin", /admin|관리자/],
    ["dashboard", /dashboard|home|홈/],
    ["tree", /tree|leaf|트리|잎/],
    ["supabase", /supabase/],
    ["api", /api|route|endpoint/],
    ["styles", /css|scss|style|theme|dark|light/],
    ["config", /config|tsconfig|eslint|tailwind|package\.json/],
    ["ui", /component|button|modal|dialog|card|ui/]
  ];

  return rules.find(([, pattern]) => pattern.test(haystack))?.[0] ?? "general";
}

function extractKeywords(path: string, content: string): string[] {
  const pathTokens = path.split(/[/.\\_-]+/g);
  const codeTokens = [
    ...content.matchAll(/\b(?:export\s+)?(?:function|const|class)\s+([A-Za-z0-9_]+)/g),
    ...content.matchAll(/\bexport\s+default\s+function\s+([A-Za-z0-9_]+)/g)
  ].map((match) => match[1]);
  const routeTokens = [...path.matchAll(/(?:app|pages)\/([^/]+)/g)].map((match) => match[1]);

  return [...new Set([...pathTokens, ...codeTokens, ...routeTokens].map(cleanKeyword).filter(Boolean))].slice(0, 40);
}

function inferFeatures(entry: ProjectIndexEntry): string[] {
  return [...new Set([entry.category, ...entry.keywords.filter((keyword) => keyword.length > 3)])].slice(0, 12);
}

function describeRole(entry: ProjectIndexEntry): string {
  if (entry.category === "config") {
    return "Project configuration or build setup file.";
  }

  if (entry.category === "styles") {
    return "Styling/theme related file.";
  }

  return `${entry.category} related code or UI file.`;
}

function extractScanTokens(text: string): string[] {
  const aliases: Record<string, string[]> = {
    설정: ["settings", "setting", "설정"],
    관리자: ["admin", "관리자"],
    의견: ["feedback", "opinion", "comment", "의견", "피드백"],
    피드백: ["feedback", "opinion", "comment", "의견", "피드백"],
    문의: ["contact", "inquiry", "support", "문의"],
    카카오: ["kakao", "카카오"],
    로그인: ["login", "auth", "로그인"],
    트리: ["tree", "leaf", "트리"],
    홈: ["home", "dashboard", "홈"]
  };
  const raw = text.toLowerCase().match(/[a-z0-9가-힣]{2,}/g) ?? [];
  const expanded = raw.flatMap((token) => aliases[token] ?? [token]);

  return [...new Set(expanded.map((token) => token.toLowerCase()))].slice(0, 30);
}

function priorityBonus(path: string, token: string): number {
  const lowerPath = path.toLowerCase();
  const highPriority = [
    "app/settings",
    "components/settings",
    "settings",
    "app/admin",
    "components/admin",
    "admin",
    "feedback",
    "contact"
  ];
  const relevantTokens = ["settings", "설정", "admin", "관리자", "feedback", "피드백", "의견", "contact", "문의"];

  if (highPriority.some((pattern) => lowerPath.includes(pattern)) && relevantTokens.includes(token)) {
    return 5;
  }

  return 0;
}

function cleanKeyword(keyword: string | undefined): string {
  if (!keyword) {
    return "";
  }

  const cleaned = keyword.trim();
  if (cleaned.length < 2 || /^\d+$/.test(cleaned)) {
    return "";
  }

  return cleaned;
}
